'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import {browserDb} from '@/lib/supabase/browser';
import {saveProduct,deleteProduct,saveContent,deleteContent,adjustStock,startUpload,finishUpload,deleteMedia,saveGallery} from '@/lib/admin/actions';
import type {Product,Content,Media,Level,Movement,Audit} from '@/lib/admin/types';

type Props={products:Product[];content:Content[];media:Media[];outlets:{id:string;name:string}[];levels:Level[];movements:Movement[];audit:Audit[];count:number;page:number;query:string};
const text=(f:FormData,k:string)=>String(f.get(k)||'');
const nullable=(f:FormData,k:string)=>text(f,k)||null;
const mediaUrl=(path:string)=>`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/website-assets/${path}`;
export default function AdminDashboard(props:Props){
 const router=useRouter();const [tab,setTab]=useState('Products');const [product,setProduct]=useState<Product|null|undefined>(undefined);const [content,setContent]=useState<Content|null|undefined>(undefined);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [stockRequest,setStockRequest]=useState(()=>crypto.randomUUID());
 async function execute(task:()=>Promise<{ok:boolean;error?:string}>,done?:()=>void){setBusy(true);setMessage('');try{const result=await task();if(!result.ok)throw new Error(result.error||'Unable to save.');setMessage('Saved successfully.');done?.();router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Operation failed.');}finally{setBusy(false);}}
 function imageSelect(value:string|null){return <label className="admin-label">Cover image<select name="image_id" defaultValue={value||''}><option value="">Keep original image / no uploaded image</option>{props.media.map(m=><option key={m.id} value={m.id}>{m.alt}</option>)}</select></label>;}
 async function submitProduct(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const raw=text(f,'price');
 await execute(()=>saveProduct({id:product?.id||null,version:product?.version||1,name:text(f,'name'),slug:product?.slug||text(f,'slug'),channel:product?.channel||text(f,'channel'),description:text(f,'description'),brand_id:nullable(f,'brand_id'),category_id:nullable(f,'category_id'),image_id:nullable(f,'image_id'),status:text(f,'status'),specs:text(f,'specs').split('\n').map(s=>s.trim()).filter(Boolean),payload:{look:text(f,'look'),format:text(f,'format'),material:text(f,'material'),finish:text(f,'finish'),applications:text(f,'applications').split(',').map(s=>s.trim()).filter(Boolean)},sku:product?.product_variants[0]?.sku||text(f,'sku'),price_paisa:raw===''?null:Math.round(Number(raw)*100),price_confirmed:f.get('confirmed')==='on',unit:text(f,'unit'),stock_status:text(f,'stock_status')}),()=>setProduct(undefined));}
 async function submitContent(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await execute(()=>saveContent({id:content?.id||text(f,'id'),kind:content?.kind||text(f,'kind'),version:content?.version||1,name:text(f,'name'),description:text(f,'description'),image_id:nullable(f,'image_id'),published:f.get('published')==='on',sort_order:Number(f.get('sort_order'))},!content),()=>setContent(undefined));}
 const variant=product?.product_variants[0];
 return <main id="main" className="mx-auto max-w-7xl"><header className="mb-8 flex flex-wrap justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-gold">MRF Galaxy</p><h1 className="mt-2 text-3xl">Store management</h1></div><div className="flex gap-3"><Link href="/" className="admin-button admin-secondary">View website</Link><button className="admin-button admin-secondary" onClick={async()=>{await browserDb().auth.signOut();router.replace('/admin/login');router.refresh();}}>Sign out</button></div></header>
 <nav className="mb-6 flex flex-wrap gap-2" aria-label="Admin sections">{['Products','Images','Homepage & categories','Inventory','Activity'].map(t=><button key={t} onClick={()=>{setTab(t);setProduct(undefined);setContent(undefined);}} className={`admin-button ${tab===t?'':'admin-secondary'}`} aria-pressed={tab===t}>{t}</button>)}</nav><p role="status" className="mb-5 text-sm">{message}</p>
 {tab==='Products'&&<>
 {product===undefined?<><div className="mb-6 flex flex-wrap justify-between gap-4"><form className="flex gap-2" action="/admin"><input name="q" defaultValue={props.query} aria-label="Search products" placeholder="Search products"/><button className="admin-button">Search</button></form><button className="admin-button" onClick={()=>setProduct(null)}>Add product</button></div><p className="mb-4 text-sm">{props.count} products · Page {props.page}</p><div className="divide-y divide-neutral-200 border border-neutral-200 bg-white">{props.products.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="font-semibold">{p.name}</h2><p className="mt-1 text-sm text-neutral-500">{p.channel} · {p.status} · {p.product_variants[0]?.sku}</p></div><button className="admin-button admin-secondary" onClick={()=>setProduct(p)}>Edit</button></div>)}</div><div className="mt-5 flex gap-3">{props.page>1&&<Link className="admin-button admin-secondary" href={`/admin?page=${props.page-1}&q=${encodeURIComponent(props.query)}`}>Previous</Link>}{props.page*20<props.count&&<Link className="admin-button admin-secondary" href={`/admin?page=${props.page+1}&q=${encodeURIComponent(props.query)}`}>Next</Link>}</div></>:
 <section className="border border-neutral-200 bg-white p-6"><h2 className="mb-6 text-2xl">{product?'Edit product':'Add product'}</h2><form onSubmit={submitProduct}><fieldset disabled={busy} className="grid gap-5 md:grid-cols-2">
 <label className="admin-label">Name<input name="name" defaultValue={product?.name} required maxLength={200}/></label><label className="admin-label">URL slug<input name="slug" defaultValue={product?.slug} readOnly={!!product} required pattern="[a-z0-9]+(-[a-z0-9]+)*"/></label>
 <label className="admin-label">Collection<select name="channel" defaultValue={product?.channel||'brand'} disabled={!!product}>{['brand','collection','sanitary','room'].map(c=><option key={c}>{c}</option>)}</select></label><label className="admin-label">SKU<input name="sku" defaultValue={variant?.sku} readOnly={!!product} required/></label>
 <label className="admin-label">Brand<select name="brand_id" defaultValue={product?.brand_id||''}><option value="">No brand</option>{props.content.filter(c=>c.kind==='brand').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <label className="admin-label">Category<select name="category_id" defaultValue={product?.category_id||''}><option value="">No category</option>{props.content.filter(c=>['room','sanitary-category'].includes(c.kind)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <label className="admin-label md:col-span-2">Description<textarea name="description" defaultValue={product?.description}/></label><label className="admin-label">Price (BDT)<input name="price" type="number" min="0" step="0.01" defaultValue={variant?.price_paisa!=null?variant.price_paisa/100:''}/></label><label className="admin-label">Selling unit<select name="unit" defaultValue={variant?.unit||'piece'}><option value="piece">Piece</option><option value="box">Box</option><option value="sq_ft">Square foot</option></select></label>
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" name="confirmed" defaultChecked={variant?.price_confirmed}/>Price verified by owner</label><label className="admin-label">Availability<select name="stock_status" defaultValue={variant?.stock_status||'unknown'}>{['unknown','in_stock','out_of_stock','preorder'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label>
 {imageSelect(product?.image_id||null)}<label className="admin-label">Publication<select name="status" defaultValue={product?.status||'draft'}>{['draft','published','archived'].map(s=><option key={s}>{s}</option>)}</select></label>
 {['look','format','material','finish','applications'].map(k=><label className="admin-label" key={k}>{k==='applications'?'Applications (comma separated)':k}<input name={k} defaultValue={Array.isArray(product?.payload[k])?(product?.payload[k] as string[]).join(', '):String(product?.payload[k]||'')}/></label>)}
 <label className="admin-label md:col-span-2">Specifications (one per line)<textarea name="specs" defaultValue={product?.specs.join('\n')}/></label><div className="flex gap-3"><button className="admin-button">Save product</button><button type="button" className="admin-button admin-secondary" onClick={()=>setProduct(undefined)}>Cancel</button></div>
 </fieldset></form>
 {product&&<><form className="mt-8 border-t pt-5" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const ids=text(f,'gallery').split(',').map(v=>v.trim()).filter(Boolean);void execute(()=>saveGallery(product.id,ids));}}><label className="admin-label">Gallery images (select in display order)<select name="gallery" multiple defaultValue={product.product_images.sort((a,b)=>a.sort_order-b.sort_order).map(i=>i.image_id)} onChange={e=>{const selected=Array.from(e.target.selectedOptions).map(o=>o.value);const hidden=e.target.form?.elements.namedItem('gallery_ids') as HTMLInputElement;if(hidden)hidden.value=selected.join(',');}}>{props.media.map(m=><option key={m.id} value={m.id}>{m.alt}</option>)}</select></label><input type="hidden" name="gallery_ids" defaultValue={product.product_images.map(i=>i.image_id).join(',')}/><button disabled={busy} className="admin-button mt-3" onClick={e=>{e.preventDefault();const f=new FormData(e.currentTarget.form!);void execute(()=>saveGallery(product.id,text(f,'gallery_ids').split(',').filter(Boolean)));}}>Save gallery</button></form>{product.status==='archived'&&<button className="admin-button admin-secondary mt-6" disabled={busy} onClick={()=>{if(window.confirm('Permanently delete this archived product? Inventory history prevents deletion.'))void execute(()=>deleteProduct(product.id),()=>setProduct(undefined));}}>Permanently delete</button>}</>}
 </section>}</>}
 {tab==='Images'&&<><form className="mb-8 grid gap-4 border bg-white p-6 md:grid-cols-3" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const file=f.get('file') as File;await execute(async()=>{if(!file||file.size>10*1024*1024)throw new Error('Choose an image up to 10 MB.');const upload=await startUpload(file.name);if(!upload.ok)throw new Error(upload.error);const {error}=await browserDb().storage.from('admin-staging').uploadToSignedUrl(upload.data.path,upload.data.token,file);if(error)throw error;return finishUpload(upload.data.path,text(f,'alt'));});}}><label className="admin-label">Image · JPEG, PNG, WebP · up to 10 MB<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/></label><label className="admin-label">Image description<input name="alt" required minLength={3} maxLength={300}/></label><button disabled={busy} className="admin-button self-end">Upload image</button></form><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{props.media.map(m=><article key={m.id} className="border bg-white p-4"><div className="relative aspect-square"><Image src={mediaUrl(m.path)} alt={m.alt} fill sizes="25vw" className="object-contain"/></div><p className="my-3 text-sm">{m.alt}</p><button className="admin-button admin-secondary" disabled={busy} onClick={()=>{if(window.confirm('Delete this image? Images in use cannot be deleted.'))void execute(()=>deleteMedia(m.id));}}>Delete</button></article>)}</div></>}
 {tab==='Homepage & categories'&&<>{content===undefined?<><button className="admin-button mb-5" onClick={()=>setContent(null)}>Add section / brand / category</button><div className="divide-y border bg-white">{props.content.map(c=><div className="flex items-center justify-between gap-4 p-5" key={c.id}><div><h2>{c.name}</h2><p className="text-sm text-neutral-500">{c.kind} · {c.published?'Published':'Hidden'}</p></div><button className="admin-button admin-secondary" onClick={()=>setContent(c)}>Edit</button></div>)}</div></>:<form onSubmit={submitContent} className="border bg-white p-6"><fieldset disabled={busy} className="grid gap-5 md:grid-cols-2"><label className="admin-label">ID / slug<input name="id" required defaultValue={content?.id} readOnly={!!content}/></label><label className="admin-label">Section type<select name="kind" defaultValue={content?.kind||'brand'} disabled={!!content}>{['brand','room','sanitary-category','hero'].map(k=><option key={k}>{k}</option>)}</select></label><label className="admin-label">Name / heading<input name="name" required defaultValue={content?.name}/></label>{imageSelect(content?.image_id||null)}<label className="admin-label md:col-span-2">Description / subtitle<textarea name="description" defaultValue={content?.description}/></label><label className="admin-label">Display order<input name="sort_order" type="number" min="0" defaultValue={content?.sort_order||0}/></label><label className="flex items-center gap-2"><input name="published" type="checkbox" defaultChecked={content?.published}/>Published</label><div className="flex gap-3"><button className="admin-button">Save content</button><button type="button" className="admin-button admin-secondary" onClick={()=>setContent(undefined)}>Cancel</button></div>{content&&!content.published&&<button type="button" className="admin-button admin-secondary" onClick={()=>{if(window.confirm('Delete this hidden content?'))void execute(()=>deleteContent(content.id),()=>setContent(undefined));}}>Delete hidden content</button>}</fieldset></form>}</>}
 {tab==='Inventory'&&<><p className="mb-4 text-sm">Adjust physical stock per outlet. Availability is managed separately on each product; unknown stock is never assumed to be available. Search products on the Products tab to change the selection below.</p><form className="grid gap-4 border bg-white p-6 md:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void execute(()=>adjustStock({variant:text(f,'variant'),outlet:text(f,'outlet'),delta:Number(f.get('delta')),reason:text(f,'reason'),request:stockRequest}),()=>setStockRequest(crypto.randomUUID()));}}><label className="admin-label">Product / SKU<select name="variant" required>{props.products.flatMap(p=>p.product_variants.map(v=><option key={v.id} value={v.id}>{p.name} · {v.sku}</option>))}</select></label><label className="admin-label">Outlet<select name="outlet" required>{props.outlets.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="admin-label">Quantity adjustment (+ received / − sold)<input name="delta" type="number" step="1" required/></label><label className="admin-label">Reason<input name="reason" required minLength={3}/></label><button disabled={busy} className="admin-button">Record adjustment</button></form><h2 className="my-5 text-xl">Current stock</h2><div className="divide-y border bg-white">{props.levels.map(l=><p className="p-4 text-sm" key={l.variant_id+l.outlet_id}>{props.products.flatMap(p=>p.product_variants).find(v=>v.id===l.variant_id)?.sku||l.variant_id} · {props.outlets.find(o=>o.id===l.outlet_id)?.name} · {l.quantity} units {l.quantity<=l.low_stock_threshold?'· Low stock':''}</p>)}</div><h2 className="my-5 text-xl">Recent movements</h2>{props.movements.map(m=><p className="border-b py-3 text-sm" key={m.id}>{m.created_at.slice(0,16).replace('T',' ')} · {m.delta>0?'+':''}{m.delta} · {m.reason}</p>)}</>}
 {tab==='Activity'&&<div className="divide-y border bg-white">{props.audit.map(a=><p key={a.id} className="p-4 text-sm">{a.created_at.slice(0,16).replace('T',' ')} · {a.action} · {a.entity} · {a.actor||'Setup / import'}</p>)}</div>}
 </main>;
}
