const fs=require('fs');
function edit(path,fn){fs.writeFileSync(path,fn(fs.readFileSync(path,'utf8')));}
edit('lib/brands.ts',s=>s.replace('priceBdt: number;','priceBdt: number | null;\n  approximate?: boolean;\n  stockStatus?: string;').replace('formatPriceBdt(price: number)','formatPriceBdt(price: number | null)').replace('return `৳${price.toLocaleString("en-BD")}`;','return price === null ? "Request price" : `৳${price.toLocaleString("en-BD")}`;'));
edit('lib/sanitaryData.ts',s=>s.replace('price: number;','price: number | null;').replace('formatPriceBdt(price: number)','formatPriceBdt(price: number | null)').replace('return `৳${price.toLocaleString("en-BD")}`;','return price === null ? "Request price" : `৳${price.toLocaleString("en-BD")}`;'));
edit('components/brands/SharifProductGrid.tsx',s=>s.replace('a.priceBdt - b.priceBdt','(a.priceBdt ?? Infinity) - (b.priceBdt ?? Infinity)').replace('b.priceBdt - a.priceBdt','(b.priceBdt ?? -Infinity) - (a.priceBdt ?? -Infinity)'));
edit('components/brands/BrandProductCard.tsx',s=>s.replace('product.priceSource ? "Approx. price"','product.priceSource || product.approximate ? "Approx. price"').replace('<div className="mt-4 border-t',`{product.stockStatus && <p className="mt-3 text-xs text-neutral-600">Availability: {product.stockStatus.replaceAll('_', ' ')}</p>}\n        <div className="mt-4 border-t`));
edit('components/CollectionSection.tsx',s=>s.replace('import { BRANDS } from "@/lib/brands";','import { getBrands, getRooms } from "@/lib/catalog";').replace('ROOM_CATEGORIES, ROOM_FILTERS','ROOM_FILTERS').replace('export default function CollectionSection() {','export default async function CollectionSection() {\n const [BRANDS,ROOM_CATEGORIES]=await Promise.all([getBrands(),getRooms()]);'));
edit('app/brands/page.tsx',s=>s.replace('import { BRANDS, type Brand } from "@/lib/brands";','import type { Brand } from "@/lib/brands";\nimport {getBrands} from "@/lib/catalog";').replace('export default function BrandsPage() {','export default async function BrandsPage() {\nconst BRANDS=await getBrands();'));
edit('app/brands/[slug]/page.tsx',s=>s.replace('from "@/lib/brands"','from "@/lib/catalog"').replace('getAllBrandSlugs().map','(await getAllBrandSlugs()).map').replaceAll('const brand = getBrandBySlug(slug);','const brand = await getBrandBySlug(slug);'));
edit('components/collection/CollectionCatalog.tsx',s=>s.replace('CATALOG_PRODUCTS, type FilterId','type CatalogProduct, type FilterId').replace('(typeof CATALOG_PRODUCTS)[number]','CatalogProduct').replace('export default function CollectionCatalog() {','export default function CollectionCatalog({products}:{products:CatalogProduct[]}) {').replace('CATALOG_PRODUCTS.filter','products.filter').replace('[activeFilters],','[activeFilters,products],'));
edit('app/collection/page.tsx',s=>'import {getCollections} from "@/lib/catalog";\n'+s.replace('export default function CollectionPage() {','export default async function CollectionPage() {\nconst products=await getCollections();').replace('<CollectionCatalog />','<CollectionCatalog products={products} />'));
edit('app/collection/[slug]/page.tsx',s=>s.replace('CATALOG_PRODUCTS,','getCollections,').replace('from "@/components/collection/collection-data"','from "@/lib/catalog"').replace('export function generateStaticParams()','export async function generateStaticParams()').replace('CATALOG_PRODUCTS.map','(await getCollections()).map').replaceAll('const product = getProductBySlug(slug);','const product = await getProductBySlug(slug);').replace('const relatedProducts = getRelatedProducts(product);','const relatedProducts = await getRelatedProducts(product);'));
edit('app/rooms/[slug]/page.tsx',s=>s.replace('from "@/components/rooms/rooms-data"','from "@/lib/catalog"').replace('from "@/lib/roomCategories"','from "@/lib/catalog"').replace('export function generateStaticParams()','export async function generateStaticParams()').replace('getAllRoomSlugs().map','(await getAllRoomSlugs()).map').replaceAll('const room = getRoomCategoryBySlug(slug);','const room = await getRoomCategoryBySlug(slug);').replace('const products = getRoomProducts(room.id);','const products = await getRoomProducts(room.id);'));
edit('app/sanitary/page.tsx',s=>s.replace('import { SANITARY_CATEGORIES } from "@/components/sanitary/sanitary-data";','import {getSanitaryCategories} from "@/lib/catalog";').replace('export default function SanitaryPage() {','export default async function SanitaryPage() {\nconst SANITARY_CATEGORIES=await getSanitaryCategories();'));
for(const path of ['app/sanitary/[slug]/page.tsx','app/sanitary/[slug]/[id]/page.tsx'])edit(path,s=>{
 s=s.replace('  formatPriceBdt,','').replace('  buildProductWhatsAppUrl,','').replace('from "@/lib/sanitaryData"','from "@/lib/catalog"');
 s='import {formatPriceBdt,buildProductWhatsAppUrl} from "@/lib/sanitaryData";\n'+s;
 return s.replace('  SANITARY_CATEGORIES,','  getSanitaryCategories,').replace('  SANITARY_PRODUCTS,','  getSanitaryProducts,').replace('SANITARY_CATEGORIES.map','(await getSanitaryCategories()).map').replace('SANITARY_PRODUCTS.map','(await getSanitaryProducts()).map').replaceAll('const category = getSanitaryCategoryBySlug(slug);','const category = await getSanitaryCategoryBySlug(slug);').replaceAll('const product = getSanitaryProductById(id);','const product = await getSanitaryProductById(id);').replace('const products = getSanitaryListingsByCategory(slug);','const products = await getSanitaryListingsByCategory(slug);');
});
edit('components/Hero.tsx',s=>s.replace('const views = [','const defaultViews = [').replace('export default function Hero() {','export default function Hero({slides}:{slides?:{src:string;alt:string;heading?:string;subtitle?:string}[]}) {\n const views=slides ?? defaultViews;').replace('useState(1)','useState(slides ? 0 : 1)').replace('  return (','  if(!views.length) return null;\n  const view=views[Math.min(active,views.length-1)];\n  return (').replaceAll('views[active].','view.').replace('Elegance in every detail','{slides ? slides[Math.min(active,slides.length-1)]?.subtitle : "Elegance in every detail"}').replace('<h1><span>GALAXY</span><span>COLLECTION</span></h1>','<h1>{slides ? <span>{slides[Math.min(active,slides.length-1)]?.heading}</span> : <><span>GALAXY</span><span>COLLECTION</span></>}</h1>'));
edit('app/page.tsx',s=>'import {getHeroSlides} from "@/lib/catalog";\n'+s.replace('export default function Home() {','export default async function Home() {\nconst slides=await getHeroSlides();').replace('<Hero />','<Hero slides={slides} />'));
edit('app/sitemap.ts',s=>s.replace('import { CATALOG_PRODUCTS } from "@/components/collection/collection-data";','import {getCollections,getSanitaryCategories,getSanitaryProducts} from "@/lib/catalog";').replace('import { SANITARY_CATEGORIES } from "@/components/sanitary/sanitary-data";','').replace('import { SANITARY_PRODUCTS } from "@/lib/sanitaryData";','').replace('from "@/lib/brands"','from "@/lib/catalog"').replace('from "@/lib/roomCategories"','from "@/lib/catalog"').replace('export default function sitemap(): MetadataRoute.Sitemap {','export default async function sitemap(): Promise<MetadataRoute.Sitemap> {\nconst [CATALOG_PRODUCTS,SANITARY_CATEGORIES,SANITARY_PRODUCTS]=await Promise.all([getCollections(),getSanitaryCategories(),getSanitaryProducts()]);').replace('getAllBrandSlugs()','await getAllBrandSlugs()').replace('getAllRoomSlugs()','await getAllRoomSlugs()'));
